name: Build and Release Windows EXE

on:
  release:
    types: [published]

jobs:
  build:
    name: Build EXE on Windows and Upload to Release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psutil requests pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile system_info_reader.py

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/system_info_reader.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
